import type { Metadata } from "next";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Scale } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service — Releasy",
  description: "Terms and conditions for using Releasy's AI-powered launch kit generator.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-1 pt-32 pb-24">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-3 mb-6">
            <div className="h-8 w-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
              <Scale className="h-4 w-4 text-primary" />
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight">Terms of Service</h1>
          </div>
          <p className="text-sm text-muted-foreground mb-10">Last updated: July 2026</p>

          <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
              <p>
                By using Releasy (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree,
                do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
              <p>
                Releasy analyzes public GitHub repository metadata and generates marketing and launch content using AI.
                The Service accesses publicly available repository information only. Private repository analysis requires
                explicit user-provided access.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">3. User Responsibilities</h2>
              <ul className="list-disc pl-5 space-y-1">
                <li>You must not use the Service for any illegal purpose</li>
                <li>You are responsible for reviewing and editing AI-generated content before publishing</li>
                <li>You must not submit repositories that contain malicious code or violate GitHub&apos;s terms</li>
                <li>You may not scrape, abuse, or overload the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">4. Intellectual Property</h2>
              <p>
                You retain full ownership of all content generated through Releasy. The Service itself, including its
                code, design, and branding, is owned by Releasy and protected by applicable laws.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">5. AI-Generated Content</h2>
              <p>
                Content is generated by AI models and may contain inaccuracies. You are solely responsible for verifying
                and editing outputs before use. Releasy makes no warranties about the accuracy, completeness, or
                suitability of generated content.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">6. Limitation of Liability</h2>
              <p>
                Releasy is provided &quot;as is&quot; without warranty of any kind. In no event shall Releasy be liable for
                any damages arising from the use of the Service.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">7. Changes to Terms</h2>
              <p>
                We reserve the right to modify these terms at any time. Continued use of the Service after changes
                constitutes acceptance of the new terms.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-foreground mb-3">8. Contact</h2>
              <p>
                For questions about these terms, email legal@releasy.sh.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
